samples/kdbus: stub out code for glibc < 2.7
Andrew Morton reports the following build error in samples/kdbus on Fedora
Core 6:

  samples/kdbus/kdbus-workers.c:73:26: error: sys/signalfd.h: No such file or directory
  samples/kdbus/kdbus-workers.c: In function 'master_new':
  samples/kdbus/kdbus-workers.c:231: warning: implicit declaration of function 'signalfd'
  samples/kdbus/kdbus-workers.c:231: error: 'SFD_CLOEXEC' undeclared (first use in this function)
  samples/kdbus/kdbus-workers.c:231: error: (Each undeclared identifier is reported only once
  samples/kdbus/kdbus-workers.c:231: error: for each function it appears in.)
  samples/kdbus/kdbus-workers.c: In function 'master_handle_signal':
  samples/kdbus/kdbus-workers.c:406: error: storage size of 'val' isn't known
  samples/kdbus/kdbus-workers.c:406: warning: unused variable 'val'
  samples/kdbus/kdbus-workers.c: In function 'child_run':
  samples/kdbus/kdbus-workers.c:773: error: 'CLOCK_MONOTONIC_COARSE' undeclared (first use in this function)
  samples/kdbus/kdbus-workers.c: In function 'bus_open_connection':
  samples/kdbus/kdbus-workers.c:1038: error: 'O_CLOEXEC' undeclared (first use in this function)
  samples/kdbus/kdbus-workers.c: In function 'bus_make':
  samples/kdbus/kdbus-workers.c:1275: error: 'O_CLOEXEC' undeclared (first use in this function)

Fedora Core 6 was released in 2006, which predates the introduction of
signalfds in the kernel (v2.6.22, 2007).

The example cannot be built without signalfds, and kbuild cannot depend on
specific features of the local libc when building userspace executables, so
we have to work around the issue by checking for specific glibc versions at
compile time and stub the entire thing if it can't be compiled.

Reported-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Daniel Mack <daniel@zonque.org>
Signed-off-by: David Herrmann <dh.herrmann@gmail.com>