iio: Use type header from kernel tree
The iio tools have been updated as new event types have been added to
the kernel. The tools currently use the standard system headers which
means that the system may not have the newest defintitions. This leads
to build failures when building newer tools on older hosts:

gcc -Wall -g -D_GNU_SOURCE   -c -o iio_event_monitor.o
iio_event_monitor.c
iio_event_monitor.c:59:3: error: ‘IIO_UVINDEX’ undeclared here (not in a
function)
  [IIO_UVINDEX] = "uvindex",
   ^~~~~~~~~~~
iio_event_monitor.c:59:3: error: array index in initializer not of
integer type
iio_event_monitor.c:59:3: note: (near initialization for
‘iio_chan_type_name_spec’)
iio_event_monitor.c:97:3: error: ‘IIO_MOD_LIGHT_UV’ undeclared here (not
in a function)
  [IIO_MOD_LIGHT_UV] = "uv",
   ^~~~~~~~~~~~~~~~
iio_event_monitor.c:97:3: error: array index in initializer not of
integer type
iio_event_monitor.c:97:3: note: (near initialization for
‘iio_modifier_names’)
<builtin>: recipe for target 'iio_event_monitor.o' failed

Switch to using the header from the kernel tree to ensure the newest
defintions are always picked up.

Signed-off-by: Laura Abbott <labbott@redhat.com>